#!/bin/bash

######## ------ PYENV SET UP --------- ##########
## This installation script is inspired by
## https://www.tecmint.com/pyenv-install-and-manage-multiple-python-versions-in-linux/
####### ------------------------------ ##########

# # Install pre-requisite
sudo apt install -qqy curl git-core gcc make zlib1g-dev libbz2-dev libreadline-dev libsqlite3-dev libssl-dev

# Clone pyenv if directory doesn't exist.
if [ ! -x "$(command -v pyenv)" ] ; then
    git clone https://github.com/pyenv/pyenv.git $HOME/.pyenv
fi

# Clone the pyenv virtualenv repo if directory doesn't exist.
if [ ! -d "$HOME/.pyenv/plugins/pyenv-virtualenv" ] ; then
    git clone https://github.com/yyuu/pyenv-virtualenv.git $HOME/.pyenv/plugins/pyenv-virtualenv
fi

source $HOME/.mybashrc
echo "pyenv installation complete."
