#!/bin/bash

######## ------ PYENV SET UP --------- ##########
## This installation script is inspired by
## https://www.tecmint.com/pyenv-install-and-manage-multiple-python-versions-in-linux/
####### ------------------------------ ##########

# # Install pre-requisite
sudo apt install -qqy curl git-core gcc make zlib1g-dev libbz2-dev libreadline-dev libsqlite3-dev libssl-dev

# Clone pyenv if directory doesn't exist.
if [ ! -x "$(command -v pyenv)" ] ; then
    git clone https://github.com/pyenv/pyenv.git $HOME/.pyenv
fi

# Clone the pyenv virtualenv repo if directory doesn't exist.
if [ ! -d "$HOME/.pyenv/plugins/pyenv-virtualenv" ] ; then
    git clone https://github.com/yyuu/pyenv-virtualenv.git $HOME/.pyenv/plugins/pyenv-virtualenv
fi

# Set root environment variable if not set.
if grep -q "PYENV_ROOT" $HOME/.bash_env; then
    echo -e "\n\$PYENV_ROOT already set."
else
    echo "export PYENV_ROOT=$HOME/.pyenv" >> $HOME/.bash_env
    echo -e "\nSetting PYENV_ROOT to $HOME/.pyenv"
fi

# Append bin environment variable to path if not set.
if grep -q "pyenv" $HOME/.bash_paths; then
    echo -e "\$PYENV_ROOT/bin already in \$PATH"
else
    echo "export PATH=$PATH:$HOME/.pyenv/bin" >> $HOME/.bash_paths
    echo -e "Adding $HOME/.pyenv/bin to PATH"
fi

# Enable shims
if command -v pyenv 1>/dev/null 2>&1; then
  eval "$(pyenv init -)"
fi

echo "pyenv installation complete."
exec "$SHELL"
